[project]
name = "ai-health-adviser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.136.0",
    "langchain>=1.2.15",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.31",
    "langchain-openai>=1.1.14",
    "langchain-text-splitters>=1.1.2",
    "motor>=3.7.1",
    "pillow>=12.2.0",
    "pypdf>=6.10.2",
    "python-dotenv>=1.2.2",
    "pytesseract>=0.3.10",
    "uvicorn>=0.44.0",
    "python-multipart>=0.0.26",
    "langchain-classic>=1.0.4",
    "jq>=1.11.0",
    "langchain-qdrant>=1.1.0",
    "qdrant-client>=1.17.1",
    "docker>=7.1.0",
    "langchain-groq>=1.1.2",
]
